# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crf_learn_ <- function(template_data, train, model, freq, max_iterations, eta, algorithm, thread) {
    .Call('crfpp_crf_learn_', PACKAGE = 'crfpp', template_data, train, model, freq, max_iterations, eta, algorithm, thread)
}

rcpp_hello <- function() {
    .Call('crfpp_rcpp_hello', PACKAGE = 'crfpp')
}

