# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crf_learn_ <- function(template_data, train, model, freq, max_iterations, cost, eta, algorithm, shrinking_size) {
    .Call('testcpp_crf_learn_', PACKAGE = 'testcpp', template_data, train, model, freq, max_iterations, cost, eta, algorithm, shrinking_size)
}

crf_test_ <- function(test_data, model, output, nbest, cost_factor) {
    .Call('testcpp_crf_test_', PACKAGE = 'testcpp', test_data, model, output, nbest, cost_factor)
}

genia_ <- function(file) {
    .Call('testcpp_genia_', PACKAGE = 'testcpp', file)
}

rcpp_hello <- function() {
    .Call('testcpp_rcpp_hello', PACKAGE = 'testcpp')
}

test <- function(xs) {
    .Call('testcpp_test', PACKAGE = 'testcpp', xs)
}

