library(Rcmdr)
rm(list = ls())
# ???????? ????????  sleep #????????????????????
attach(sleep)
group1 <- sleep[group == 1, 1]
group2 <- sleep[group == 2, 1]
shapiro.test(group1)
shapiro.test(group2)
cor.test(group1, group2)
var.test(group1, group2)
t.test(group1, group2)
detach()
rm(list = ls())

# ???? ??????
attach(chickwts)
chickwts
shapiro.test(chickwts[feed == "horsebean", 1])
shapiro.test(chickwts[feed == "linseed", 1])
var.test(chickwts[feed == "horsebean", 1], chickwts[feed == "linseed", 1])
cor.test(chickwts[feed == "horsebean", 1], chickwts[feed == "linseed", 1])  #??????????????????????
plot(chickwts[feed == "horsebean", 1], chickwts[feed == "linseed", 1])
# ????????????
zuoye02 = read.table("E:\\????\\advanced biostatistics\\0413??????\\????????.txt")
attach(zuoye02)
shapiro.test(V1)
shapiro.test(V2)
var.test(V1, V2)
cor.test(V1, V2)
t.test(V1, V2, paired = T)
# ????????
detach()
rm(list = ls())
library(car)
zuoye03 = read.table("E:\\????\\advanced biostatistics\\0413??????\\??????????.txt")
attach(zuoye03)
shapiro.test(V1)
shapiro.test(V2)
temp <- data.frame(c(V1, V2), rep(c("A", "B"), c(10, 10)))
colnames(temp) <- c("num", "factor")
leveneTest(temp$num ~ temp$factor)
cor.test(V1, V2, method = "kendall")  #????????????????????????????????????
wilcox.test(V1, V2, paired = T)
# ??????????
aa <- c(V1, V2)
View(aa)
rm(list = ls())
zuoye04 = read.table("E:\\????\\advanced biostatistics\\0413??????\\????????????.txt")
attach(zuoye04)
shapiro.test(V1)
shapiro.test(V2)
cor.test(V1, V2, method = "kendall")
wilcox.test(V1, V2)


# fisher exact test
zuoye05 = matrix(c(4, 5, 18, 6), 2, 2, dimnames = list(c("pre", "nonpre"), c("+", 
    "-")))
zuoye05
fisher.test(zuoye05, alternative = "t", simulate.p.value = T, B = 10000)
detach()
rm(list = ls())
library(Rcmdr)
zuoye07 <- read.table("E:\\????\\advanced biostatistics\\0413??????\\??????????????????.txt")
attach(zuoye07)
shapiro.test(zuoye06[V2 == "A", 1])
shapiro.test(zuoye06[V2 == "B", 1])
shapiro.test(zuoye06[V2 == "C", 1])
shapiro.test(zuoye06[V2 == "D", 1])
leveneTest(V1 ~ V2, center = "mean")  #????????
# leveneTest(V1~V2,center='median')
model <- aov(V1 ~ V2)
summary(model)
# ????????????????????????
model.tables(model, type = "effect")
model.tables(model, type = "mean")
tu <- TukeyHSD(model, "V2")
tu
plot(tu)
detach()

# ????????????
library(car)
zuoye07 <- read.table("E:\\????\\advanced biostatistics\\0413??????\\??????????????????.txt")
attach(zuoye07)
shapiro.test(zuoye07[V2 == "A", 1])
shapiro.test(zuoye07[V2 == "B", 1])
shapiro.test(zuoye07[V2 == "C", 1])
shapiro.test(zuoye07[V2 == "D", 1])
leveneTest(V1 ~ V2, center = "mean")
model <- aov(V1 ~ V2)
summary(model)
# ????????????????????????
model.tables(model, type = "effect")
model.tables(model, type = "mean")

detach()

rm(list = ls())
zuoye08 <- read.table("E:\\????\\advanced biostatistics\\0413??????\\??????????????????????.txt")
attach(zuoye08)
library(Rcmdr)
shapiro.test(zuoye08[V2 == "A", 1])
shapiro.test(zuoye08[V2 == "B", 1])
shapiro.test(zuoye08[V2 == "C", 1])
shapiro.test(zuoye08[V2 == "D", 1])
leveneTest(V1 ~ V2, center = "median")
kruskal.test(V1 ~ V2)
# ??????????

detach()
library(car)
zuoye09 <- read.table("E:\\????\\advanced biostatistics\\0413??????\\??????????????????.txt")
aaa <- attach(zuoye09)
stack(zuoye09)
shapiro.test(zuoye09[V2 == "A", 1])
shapiro.test(zuoye09[V2 == "B", 1])
shapiro.test(zuoye09[V2 == "C", 1])
shapiro.test(zuoye09[V2 == "D", 1])
leveneTest(V1 ~ V2, center = "median")
# ??????????4??????
matrix <- as.matrix(zuoye09)
matrix <- matrix(V1, 10, 4)
cor(matrix)

matrix
matrix[, 1] <- as.numeric(matrix[, 1])
class(matrix)
aa <- read.table("E:\\aa.txt")
cor(aa)
rm(list = ls())
attach(InsectSprays)
shapiro.test(InsectSprays[spray == "A", 1])
shapiro.test(InsectSprays[spray == "B", 1])
shapiro.test(InsectSprays[spray == "C", 1])
shapiro.test(InsectSprays[spray == "D", 1])
shapiro.test(InsectSprays[spray == "E", 1])
shapiro.test(InsectSprays[spray == "F", 1])
cor.test(count ~ spray)
test <- as.matrix(InsectSprays)
cor(test)
cor.test(test)
cor(as.matrix(InsectSprays))
`?`(cor)
re <- TukeyHSD(V1, V2)

detach()

rm(list = ls())
library(Rcmdr)
zuoye09 <- read.table("E:\\????\\advanced biostatistics\\0413??????\\??????????????????.txt")
attach(zuoye09)
shapiro.test(V1)
shapiro.test(V2)
shapiro.test(V3)
shapiro.test(V4)
temp <- stack(zuoye09)
attach(temp)
leveneTest(values ~ ind, data = temp, center = "median")
cor(zuoye09, method = "kendall")
friedman.test(as.matrix(zuoye09))
aggregate(temp, by = ind, FUN = mean)

zuoye10 <- read.table("E:\\????\\advanced biostatistics\\0413??????\\??????????????????.txt")
zuoye10
attach(zuoye10)
shapiro.test(zuoye10[V2 == "A1", 1])
shapiro.test(zuoye10[V2 == "A2", 1])
shapiro.test(zuoye10[V2 == "A3", 1])
shapiro.test(zuoye10[V2 == "A4", 1])
shapiro.test(zuoye10[V3 == "B1", 1])
shapiro.test(zuoye10[V3 == "B2", 1])
shapiro.test(zuoye10[V3 == "B3", 1])
shapiro.test(zuoye10[V3 == "B4", 1])
shapiro.test(zuoye10[V3 == "B5", 1])
shapiro.test(zuoye10[V3 == "B6", 1])
shapiro.test(zuoye10[V3 == "B7", 1])
shapiro.test(zuoye10[V3 == "B8", 1])
shapiro.test(zuoye10[V3 == "B9", 1])
shapiro.test(zuoye10[V3 == "B10", 1])
shapiro.test(zuoye10[V3 == "B11", 1])
shapiro.test(zuoye10[V3 == "B12", 1])
shapiro.test(zuoye10[V3 == "B13", 1])
shapiro.test(zuoye10[V3 == "B14", 1])
shapiro.test(zuoye10[V3 == "B15", 1])
leveneTest(V1 ~ V2, center = "mean")
leveneTest(V1 ~ V3, center = "mean")
fit <- aov(V1 ~ V2 + V3)
summary(fit)
tu <- TukeyHSD(fit)
plot(tu)
tu 
