library(car)
genchang <- read.csv("D:\\DeskTop\\yachang.csv")
genchang <- genchang[1:95, ]
genchang <- stack(genchang)
attach(genchang)
class(ind)
class(genchang)
factor(genchang)
shapiro.test(genchang[ind == "CK", 1])
shapiro.test(genchang[ind == "X0", 1])
shapiro.test(genchang[ind == "X10.2", 1])
shapiro.test(genchang[ind == "X10.4", 1])
shapiro.test(genchang[ind == "X10.1", 1])
shapiro.test(genchang[ind == "X1", 1])
shapiro.test(genchang[ind == "X20", 1])
shapiro.test(genchang[ind == "X50", 1])
leveneTest(values ~ ind)
model <- aov(values ~ ind)
result <- summary(model)
model.tables(model, type = "effect")
model.tables(model, type = "mean")
tu <- TukeyHSD(model, "ind")
tu
class(values)
genchang[, 1] 
