# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

genia <- function(file) {
    .Call('genia_genia', PACKAGE = 'genia', file)
}

rcpp_hello <- function() {
    .Call('genia_rcpp_hello', PACKAGE = 'genia')
}

